name: Compare Artifacts and Comment

on:
  pull_request:
    branches: [master, staged, dev]
    types: [opened, reopened, synchronize]

jobs:
  compare-and-comment:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“ƒ Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: â¬‡ï¸ Download artifact from feature branch
        uses: actions/download-artifact@v4
        with:
          name: metric-report.md
          # The path to place the downloaded artifact
          path: ${{ github.workspace }}/feature-branch-report

      - name: ðŸ“ƒ Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: â¬‡ï¸ Download artifact from dev branch
        uses: actions/download-artifact@v4
        with:
          name: metric-report.md
          path: ${{ github.workspace }}/dev-report

      - name: ðŸ” Compare artifacts
        run: |
          diff -u ${{ github.workspace }}/dev-report/metric-report.md ${{ github.workspace }}/feature-branch-report/metric-report.md > diff.txt || true

      - name: ðŸ’¬ Post differences as comment
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            ## Differences in Artifacts
            ```diff
            $(cat diff.txt)
            ```
