name: Compare Artifacts and Comment

on:
  pull_request:
    branches: [master, staged, dev]
    types: [opened, reopened, synchronize]

jobs:
  compare-and-comment:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“ƒ Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ðŸŽ‹ Set branch name environment variable
        run: |
          if [[ $GITHUB_REF == refs/pull/* ]]; then
            echo "BRANCH_NAME=${GITHUB_HEAD_REF}" >> $GITHUB_ENV
          else
            echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
          fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: â¬‡ï¸ Download artifact from feature branch
        run: |
          aws s3 cp ${{ secrets.AWS_S3_BUCKET }}/metric-report-${{ env.BRANCH_NAME }}.md ${{ github.workspace }}/feature-branch-report/metric-report.md

      - name: â¬‡ï¸ Download Report from Dev Branch
        run: |
          aws s3 cp ${{ secrets.AWS_S3_BUCKET }}/metric-report-${{ env.BRANCH_NAME }}.md ${{ github.workspace }}/dev-report/metric-report.md

      - name: ðŸ” Compare Reports
        run: |
          diff -u ${{ github.workspace }}/dev-report/metric-report.md ${{ github.workspace }}/feature-branch-report/metric-report.md > diff.txt || true

      - name: ðŸ’¬ Post differences as comment
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            ## Differences in Artifacts
            ```diff
            $(cat diff.txt)
            ```
